### ISSUE TITLE
About DashD

### ISSUE THREAD

**Issue by mishoboss** [EliasStar/DashD#1]
The DashD project seems exactly what I'm looking for to put on my armbian boards around my home and turn them into proper kiosks. I'm really excited about the HTTP control (make a request to a particular display to load a web page). However I have no idea how to use the DashD binary. There's no documentation available. I tried to wild guess it, but so far unsuccessfully. Can you please provide such information in the README, plus an example? Really, really thank you!

**Comment by EliasStar** [comment]
Thanks for reaching out!
This project is a work in progress, so no wonder you didn't find proper documentation. However the functionality you require is already present. I'll write some docs in a bit (probably toady or tomorrow).

**Comment by EliasStar** [comment]
Finished the docs, closing.
