### ISSUE TITLE
Do we need a full-blown Gnome?

### ISSUE THREAD

**Issue by mishoboss** [EliasStar/DashD#2]
Do we need a full-blown Gnome? I'm trying to setup DashD on Armbian without GUI.  I see that we can use xX.Org Server for a window manager. I'm unable to install `gtk-3` however on the Debian Bullseye Armbian (it says there's no such package). Can you please state minimum software requirements?

**Comment by EliasStar** [comment]
You don't need GNOME. Just install `gtk-3.0` and `webkit2gtk-4.0`. Also check the README for a possible autostart setup.
