### ISSUE TITLE
Make features disableable

### ISSUE THREAD

**Issue by mishoboss** [EliasStar/DashD#5]
**Description**
<img width="737" alt="image" src="https://user-images.githubusercontent.com/1629929/174664253-9e4ca343-cf9a-41ef-af1e-83fe90f9157a.png">

**How To Reproduce**
> Run `sudo /usr/local/sbin/dashd` on non-raspberry arm board and no ws2811 hardware.

Any way we can disable Lighting if it's not used?

**Comment by EliasStar** [comment]
The modules can now be disabled with flags. By default all are enabled, however with `--lighting_enabled=false` for example you can now disable lighting. Look up the other flags in the README.
